// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/overridesh/sgg-todolist-service/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// CommentRepository is an autogenerated mock type for the CommentRepository type
type CommentRepository struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: _a0, _a1
func (_m *CommentRepository) CreateComment(_a0 context.Context, _a1 model.Comment) (*model.Comment, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.Comment
	if rf, ok := ret.Get(0).(func(context.Context, model.Comment) *model.Comment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Comment) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCommentByTaskIdAndCommentId provides a mock function with given fields: ctx, taskId, commentId
func (_m *CommentRepository) DeleteCommentByTaskIdAndCommentId(ctx context.Context, taskId uuid.UUID, commentId uuid.UUID) error {
	ret := _m.Called(ctx, taskId, commentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, taskId, commentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCommentsByTaskId provides a mock function with given fields: _a0, _a1
func (_m *CommentRepository) GetCommentsByTaskId(_a0 context.Context, _a1 uuid.UUID) ([]*model.Comment, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*model.Comment
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Comment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Comment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
